# Generated by Django 3.0.2 on 2020-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NTU video', max_length=150)),
                ('desc', models.TextField(max_length=400)),
                ('video', models.FileField(default='.', upload_to='video_uploads/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.CharField(max_length=150)),
                ('courseCode', models.CharField(max_length=40)),
            ],
        ),
    ]
