# Generated by Django 3.0.2 on 2020-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150)),
                ('courseCode', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Baby Yoda drinking soup', max_length=150, unique=True)),
                ('desc', models.TextField(max_length=400)),
                ('video', models.FileField(default='BabyYoda.mp4', upload_to='video_uploads/')),
                ('thumbnail', models.ImageField(default='default-thumbnail.png', upload_to='thumbnails/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
