# Generated by Django 3.0.2 on 2020-01-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidboard', '0002_auto_20200114_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='NTU video', max_length=150, unique=True),
        ),
    ]
