# Generated by Django 3.0.2 on 2020-01-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidboard', '0002_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='vidboard.Course'),
        ),
    ]
