# Generated by Django 3.0.2 on 2020-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidboard', '0003_auto_20200114_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='uploadDate',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Baby Yoda drinking soup', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='BabyYoda.mp4', upload_to='video_uploads/'),
        ),
    ]
