# Generated by Django 3.0.2 on 2020-01-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidboard', '0004_auto_20200115_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail.png', upload_to='thumbnails/'),
        ),
    ]
